### ISSUE TITLE
Addition of a build system generator

### ISSUE THREAD

**Issue by elfring** [jspahrsummers/Arbiter#41]
I suggest to reuse a higher level build system than [your current small make file](https://github.com/jspahrsummers/Arbiter/blob/18fabb03d64bfd4f36e17124eab640f1b4771ee2/Makefile#L1 "Update candidate") so that powerful checks for software features will become easier.
* [CMake](https://cmake.org/ "CMake build system")
* [Autotools](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Introduction.html "GNU build system")

**Comment by jspahrsummers** [comment]
Thanks for the suggestion.

Although I agree that the current Makefile setup isn't ideal, there hasn't been a compelling reason to make the switch yet. "Powerful checks for software features" is great in the abstract, but not really an immediate problem that needs addressing—e.g., I don't know anywhere that we need conditional compilation right now. There's also an argument (that I'm sympathetic to) which suggests that [complicated automatic configuration tools are a self-fulfilling problem](http://queue.acm.org/detail.cfm?id=2349257).

This isn't to say that we shouldn't change—I would just like to understand better _why_ we should before making it happen. We've already been talking about cmake [to address some rebuilding issues](https://github.com/jspahrsummers/Arbiter/issues/28), for example.

**Comment by elfring** [comment]
* Does [a tool like "autoscan"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/autoscan-Invocation.html "Using autoscan to create configure.ac") show any software dependencies that you find worth for further considerations?
* How do you think about to support more development environments by [the reuse of build system generators](https://cmake.org/cmake/help/v3.5/manual/cmake-generators.7.html#cmake-generators "Selection for build tool generators")?

**Comment by jspahrsummers** [comment]
If there's a specific compatibility problem that you are (or anyone else is) aware of that's blocking usage, I'd love to hear about it and fix it up.

Until then, this sounds like [YAGNI](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it).
